version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore-cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: yarn install
      - save-cache:
          name: Save Yarn Package Cache
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Build Project
          command: yarn build
      - run:
          name: Deploy to Firebase
          command: yarn deploy
