version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore-cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: yarn install
      - save-cache:
          name: Save Yarn Package Cache
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Run Coverage
          command: mkdir /tmp/reports && JEST_JUNIT_OUTPUT="/tmp/reports/test-report.xml" yarn test --ci --coverage --testResultsProcessor="jest-junit"
      - store_test_results:
          path: /tmp/reports
      - run:
          name: Run Tests - Jest
          command: yarn test --bail --ci
      - run:
          name: Build Project
          command: yarn build
      - deploy:
          name: Deploy to Firebase
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
            fi
