jobs:
  build:
    docker:
      - image: circleci/node:10.15.0-jessie
    steps:
      - checkout
      - restore-cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: |
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save-cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Build Project
          command: yarn build
      - run:
          name: Deploy to Firebase
          command: yarn deploy
